sudo: false
dist: trusty

language: python

python:
    - 3.5
    - 3.6

install:
    - pip3 install neovim
    - pip3 install mypy
    - pip3 install flake8
    - pip3 install vim-vint
    - pip3 install pytest
    - pip3 install pytest-cov
    - pip3 install codecov
    - pip3 install covimerage
    - git clone --depth 1 https://github.com/thinca/vim-themis

env:
    - THEMIS_VIM=nvim
    - THEMIS_ARGS="-e -s --headless"
    - THEMIS_PROFILE_LOG=profile.txt

script:
    - vint plugin/
    - vint autoload/
    - flake8 rplugin/python3/
    - mypy --ignore-missing-imports rplugin/python3/
    - python3 -m pytest
    - ./vim-themis/bin/themis
    - covimerage write_coverage $THEMIS_PROFILE_LOG
    - codecov --file .coverage .coverage.covimerage
