sudo: false
dist: trusty

language: python

python:
    - 3.5
    - 3.6
    - "3.7-dev"

install:
    - apt-get install fuse
    - modprobe fuse
    - groupadd fuse
    - user="$(whoami)"
    - usermod -a -G fuse $user
    - wget -nv https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - mkdir -p ~/neovim/bin
    - cp nvim.appimage ~/neovim/bin/nvim
    - chmod u+x ~/neovim/bin/nvim
    - pip3 install neovim
    - pip3 install mypy
    - pip3 install flake8
    - pip3 install vim-vint
    - pip3 install pytest
    - pip3 install pytest-cov
    - pip3 install codecov
    - pip3 install covimerage
    - git clone --depth 1 https://github.com/thinca/vim-themis vim-themis

env:
    global:
        - THEMIS_VIM=nvim
        - THEMIS_ARGS="-e -s --headless"
        - THEMIS_PROFILE_LOG=profile.txt

script:
    - make lint
    - PATH="./vim-themis/bin:$HOME/neovim/bin:$PATH" THEMIS_HOME=./vim-themis make test

after_success:
    - covimerage write_coverage $THEMIS_PROFILE_LOG
    - python3 -m coverage xml --rcfile=.vim_coveragerc -o vim_coverage.xml
    - python3 -m coverage xml --rcfile=.coveragerc -o python_coverage.xml
    - codecov -f vim_coverage.xml python_coverage.xml
