sudo: false
dist: trusty

language: python

python:
    - 3.5
    - 3.6

install:
    - pip3 install neovim
    - pip3 install mypy
    - pip3 install flake8
    - pip3 install vim-vint
    - pip3 install pytest
    - pip3 install pytest-cov
    - pip3 install codecov

script:
    - vint plugin/
    - vint autoload/
    - flake8 rplugin/python3/
    - mypy --ignore-missing-imports rplugin/python3/
    - python3 -m pytest
    - codecov
