dist: trusty

language: python

python:
    - 3.5
    - 3.6
    - "3.7-dev"

install:
    - sudo modprobe fuse
    - user="$(whoami)"
    - sudo usermod -a -G fuse $user
    - wget -nv https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    - mkdir -p ~/neovim/bin
    - cp nvim.appimage ~/neovim/bin/nvim
    - chmod u+x ~/neovim/bin/nvim
    - ln -s $VIRTUAL_ENV ./curstr_env
    - ./curstr_env/bin/pip install -r ./requirements.txt
    - ./curstr_env/bin/pip install codecov
    - git clone --depth 1 https://github.com/thinca/vim-themis vim-themis

env:
    global:
        - THEMIS_VIM=nvim
        - THEMIS_ARGS="-e -s --headless"
        - THEMIS_PROFILE_LOG=profile.txt

script:
    - make lint
    - PATH="./vim-themis/bin:$HOME/neovim/bin:$PATH" THEMIS_HOME=./vim-themis make test

after_success:
    - ./curstr_env/bin/covimerage write_coverage $THEMIS_PROFILE_LOG
    - ./curstr_env/bin/coverage xml --rcfile=.vim_coveragerc -o vim_coverage.xml
    - ./curstr_env/bin/coverage xml --rcfile=.coveragerc -o python_coverage.xml
    - ./curstr_env/bin/codecov -f vim_coverage.xml python_coverage.xml
