name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout themis.vim
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Add themis to path
        run: |
          echo "::add-path::./vim-themis/bin"

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: pip install -r ./requirements.txt

      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_HOME: ./vim-themis
        run: make _test
